events:
  - type: Mail
    subType: Single
    impl: ./srv/EventQueueMail
    load: 10
    parallelEventProcessing: 5

periodicEvents:
  - type: HealthCheck
    subType: DB
    impl: "./srv/EventQueueHealthCheckDb"
    load: 80
    transactionMode: isolated
    interval: 15
  - type: HealthCheckMJS
    subType: DB
    impl: "./srv/EventQueueHealthCheckDb.mjs"
    load: 80
    transactionMode: isolated
    interval: 15
  - type: HealthCheckCJS
    subType: DB
    impl: "./srv/EventQueueHealthCheckDb.cjs"
    load: 80
    transactionMode: isolated
    interval: 15
